import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavbarDemo from "./components/NavbarDemo";
import BackgroundBeamsWithCollisionDemo from "@/app/components/herosection";
import ThreeDCardDemo from "@/app/components/head";

// import BentoGridDemo from "@/app/components/actitivies"
import TechTeamCards from "@/app/components/teams/membars"
import MeteorsDemo from "@/app/components/meteors"
import MeteorsD from "@/app/components/domain"
import Slider from "@/app/components/Slider"
import Footer from "./components/Footer";
import OperationalTeamCarouselDemo from "@/app/components/teams/operation"
import CreativeTeamCarouselDemo from "@/app/components/teams/creative"
import DesignTeamCarouselDemo from "@/app/components/teams/design"
import CONTENT from "@/app/components/teams/content"
import LLCTeamCarouselDemo from "@/app/components/teams/llc"
import Outreach from "@/app/components/teams/outreachandcom"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MLSA DYPCET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarDemo />

        <BackgroundBeamsWithCollisionDemo />
        <Slider />
        <MeteorsDemo />

        <MeteorsD />

        <div className="flex place-content-around ">
          <ThreeDCardDemo />
        </div>

        <div className="">
          <TechTeamCards />
          <LLCTeamCarouselDemo />
          <OperationalTeamCarouselDemo />
          <CreativeTeamCarouselDemo />
          <Outreach />
          <CONTENT />
          <DesignTeamCarouselDemo />

        </div>
        <Footer />
        {children}
      </body>
    </html>
  );
}
